# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Christoph Stich
tagline:          'XYZ'
description:      'PhD student at the intersection of geography and computer science'
url:              http://cstich.github.io
baseurl:          /

author:
  name:           'Christoph Stich'
  url:            https://twitter.com/cstich

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           


exclude: [vendor,CNAME,README.md]

pages_list:       
  About: '/about'
  Archive: '/archive'
  Categories: '/catalog'
  Feed: '/atom.xml'

mapbox-token: pk.eyJ1IjoiY3N0aWNoIiwiYSI6IlZCRVBhR2MifQ.NIhxFR5_gG6IhVaVyX_UxA
mapid: cstich.41df8321
mapboxjs: v2.1.5

